source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'AzureStorageApiClient_Example', :exclusive => true do
  pod "AzureStorageApiClient", :path => "../"
end

target 'AzureStorageApiClient_Tests', :exclusive => true do
  pod "AzureStorageApiClient", :path => "../"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
end
